spring:
  profiles:
    active: local # 기본적으로 local 프로파일을 활성화
external:
  public:
    min-wage:
      url: ${MIN_WAGE_URL}
      api-url: ${MIN_WAGE_API_URL}
      params:
        serviceKey: ${PUBLIC_PARAMS_SERVICE_KEY}
      headers:
        Authorization: ${PUBLIC_AUTHORIZATION}
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod
